Solution1/MVC/Controllers/DepartamentoJSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class DepartamentoJSController : Controller
    {
        //
        // GET: /DepartamentoJS/
        public ActionResult GetAll()
        {
            return View();
        }
	}
}

Solution1/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  
                    <li>@Html.ActionLink("Departamento", "GetAll", "Departamento")</li>
                    <li>@Html.ActionLink("Producto", "GetAll", "Producto")</li>
                    <li>@Html.ActionLink("Venta", "GetAll", "Venta")</li>
                    <li>@Html.ActionLink("Usuario", "GetAll", "Usuario")</li>   
                    <li>@Html.ActionLink("Login", "IniciarSesion", "Login")</li>  
                    <li>@Html.ActionLink("Departamento JavaScript", "GetAll", "DepartamentoJS")</li>
                </ul>
            
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript">
        $(document).ready(function () {


           $("#Area").change(function () {
                $("#Departamento").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetDepartamento")',
                    dataType: 'json',
                    data: { IdArea: $("#Area").val() },
                    success: function (departamentos) {
                        $.each(departamentos, function (i, departamentos) {
                            $("#Departamento").append('<option value="'
                                                       + departamentos.Value + '">'
                                                       + departamentos.Text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed.' + ex);
                    }
                });
           });

        })

    </script>






</body>
</html>