Solution1/MVC/Controllers/DepartamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace MVC.Controllers
{
    public class DepartamentoController : Controller
    {
        [HttpGet]
        public ActionResult GetAll() //webAPI
        {
            ML.Result result = BL.Departamento.GetAllWebAPI();
            ML.Departamento departamento = new ML.Departamento();
            departamento.Departamentos = result.Objects;

            return View(departamento);
                
        
        }
        // GET: Departamento
        /*[HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = BL.Departamento.GetAllEF();

            ML.Departamento departamento = new ML.Departamento();
            departamento.Departamentos = result.Objects;

            return View(departamento);

        }*/

        [HttpGet]//Mostrar el formulario
        public ActionResult Form(int? IdDepartamento) //Add , UpdateC:\Users\ALIEN 16\Documents\PGonzalez\ejemploMVC\JTorresEjemploProgramacionNCapas\PL_MVC2\Scripts\
        {
            ML.Departamento departamento = new ML.Departamento();

            ML.Result resultAreas = BL.Area.GetAllEF();
            departamento.Area = new ML.Area();
            departamento.Area.Areas = resultAreas.Objects;
            //ML.Result resultAreas= BL.Area.GetAll();


            //materia.Semestre = new ML.Semestre();
            //materia.Semestre.Semestres = resultSemestres.Objects;

            //materia.Area = new ML.Area();
            //materia.Area.Areas = resultAreas.Objects;


            if (IdDepartamento == null)//Add
            {
                return View(departamento);
            }
            else //Update
            {
                ML.Result result = BL.Departamento.GetByIdWebAPI(IdDepartamento.Value);

                if (result.Correct)
                {
                    departamento.IdDepartamento = ((ML.Departamento)result.Object).IdDepartamento;
                    departamento.Nombre = ((ML.Departamento)result.Object).Nombre;
                 
                    departamento.Area.IdArea = ((ML.Departamento)result.Object).Area.IdArea;
                   
                    //materia.Semestre.IdSemestre = ((ML.Materia)result.Object).Semestre.IdSemestre;


                    return View(departamento);
                }
                else
                {
                    ViewBag.Message = result.ErrorMessage;
                    return PartialView("Modal");
                }
            }


        }

        //public byte[] ConvertToBytes(HttpPostedFileBase Imagen)
        //{
        //    byte[] data = null;
        //    System.IO.BinaryReader reader = new System.IO.BinaryReader(Imagen.InputStream);
        //    data = reader.ReadBytes((int)Imagen.ContentLength);

        //    return data;
        //}



        [HttpPost] //Recibir datos del formulario
        public ActionResult Form(ML.Departamento departamento)
        {
            // ML.Materia materia = new ML.Materia();
            ML.Result result = new ML.Result();

            //HttpPostedFileBase file = Request.Files["ImagenData"];
            //if (file.ContentLength > 0)
            //{
            //    materia.Imagen = ConvertToBytes(file);
            //}

            if (departamento.IdDepartamento == 0)//Add
            {
                result = BL.Departamento.AddWebAPI(departamento);
                ViewBag.Message = "El departamento se agregó correctamente ";
            }
            else //Update
            {
                 
                result = BL.Departamento.UpdateWebAPI(departamento);

                ViewBag.Message = "El departamento se actualizó correctamente ";
            }

            if (!result.Correct)
            {
                ViewBag.Message = "No se pudo agregar correctamente el departamento " + result.ErrorMessage;
            }

            return PartialView("Modal");
        }

        [HttpGet]
        public ActionResult Delete(int IdDepartamento)
        {

            ML.Result result = BL.Departamento.DeleteWebAPI(IdDepartamento);

            return RedirectToAction("GetAll");
        }

      
	}
}

Solution1/MVC/Views/Departamento/Form.cshtml
@model ML.Departamento
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h5>Departamento</h5>
        </div>
    </div>

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Departamento", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.IdDepartamento, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdDepartamento, new { @class = "form-control hidden" })
                            @Html.ValidationMessageFor(model => model.IdDepartamento)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Nombre)
                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Nombre)
                        </div>
                    </div>
                 
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Area.IdArea)
                            @Html.DropDownListFor(model => model.Area.IdArea, new SelectList(Model.Area.Areas, "IdArea","Nombre"), "Selecciona un Area correspondiente", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Area.IdArea)
                        </div>
                    </div>

                    <br />

                  

                    <br />

                    @*<div class="form-group">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.Semestre.IdSemestre)
                                @Html.DropDownListFor(model => model.Semestre.IdSemestre, new SelectList(Model.Semestre.Semestres, "IdSemestre", "Nombre"), "Selecciona un semestre correspondiente", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Semestre.IdSemestre)
                            </div>
                        </div>*@

                    <div class="form-group">
                        <div class="col-md-3">
                            @*@Html.LabelFor(model => model.Imagen)*@
                            @*<input type="file" name="ImagenData" onchange="readURL(this);">*@
                            @*@if (Model.Imagen != null)
                                {

                                    <img id="ImagenPreview" src="data:image/jpeg;base64,@Convert.ToBase64String(Model.Imagen)" width="100" height="100" />
                                }
                                else
                                {
                                    <img id="ImagenPreview" src="~/Content/SIN-IMAGEN.jpg" style=" height:150px; width:150px;" />

                                }

                                @Html.ValidationMessageFor(model => model.Imagen)*@
                        </div>

                    </div>

                    @*@Html.HiddenFor(model => model.Imagen)*@

                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    @*<script type="text/javascript">
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#ImagenPreview').attr('src', e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }


        </script>*@
</div>

Solution1/MVC/Views/Departamento/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-md-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>