Solution1/MVC/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class CarritoController : Controller
    {
       
        //
        // GET: /Carrito/

        public ActionResult GetAll()
        {
            ML.Result result = new ML.Result();
            result.Objects = new List<Object>();
            result.Objects = (List<Object>)Session["Carrito"];
            return View(result);
        }

        public ActionResult AddProduct(int Id)
        {
            ML.Producto producto = new ML.Producto();

            if (Session["Carrito"] == null)
            {
                ML.Result result = new ML.Result();
                producto.IdProducto = Id;
                var resultProducto = BL.Producto.GetByIdEF(producto.IdProducto);
                result.Objects = new List<Object>();

                ML.Producto productoItem = new ML.Producto();
                ML.Producto productos = new ML.Producto();
                productoItem = (ML.Producto)resultProducto.Object;
                productoItem.VentaProducto = new ML.VentaProducto();
                productoItem.Cantidad = 1;
                productoItem.VentaProducto.Venta = new ML.Venta();


                result.Objects.Add(productoItem);
                Session["Carrito"] = result.Objects;

                return View("GetAll", result);
            }
            else
            {
                              

                                producto.IdProducto = Id;
                                
                                var result = BL.Producto.GetByIdEF(producto.IdProducto);
                               
                                result.Objects = (List<Object>)Session["Carrito"];
  
                                int pos = 0;
                                bool comprobar = false;

                                foreach (ML.Producto productos in result.Objects) //compara toda la lista que ya tenemos con el nuevo producto
                                {
                                    if (productos.IdProducto == Id)
                                    {
                                        comprobar = true;
                                        pos = productos.IdProducto;
                                    }
                                   // else
                                   // {
                                   //     comprobar = false;
                                   // }
                                }


                                if (comprobar == true) //cuando es el mismo producto
                                {
                                    foreach (ML.Producto productos in result.Objects.ToList())
                                    {
                     
                                        if (productos.IdProducto == pos)
                                        {   
                                                                                                                        
                                            productos.Cantidad++;
                                            productos.VentaProducto.Venta.Total = productos.Cantidad * productos.PrecioUnitario;                  
                                            break;
                                        }
                                    }
                                }
                                else //cuando es un nuevo producto
                                {
                                    ML.Producto productoItem = new ML.Producto(); //se crea para aumentar Cantidad
                                    productoItem = (ML.Producto)result.Object; // cast de result object a producto
                                    productoItem.Cantidad = 1;                   //asigno valor
                                    result.Objects.Add(result.Object);             //despues de añadir Cantidad lo añadimos nuevamente a la lista
                                    Session["Carrito"] = result.Objects;
                                }

                                return View("GetAll", result);

            }
        }

        public ActionResult DeleteProduct(int Id)
        {

            TempData["alertMessage"] = "Producto Eliminado";
            ML.Result result = new ML.Result();
            result.Objects = new List<Object>();
            result.Objects = (List<Object>)Session["Carrito"];
            int pos = 0;

            if (result.Objects.Count == 0)
            {
                TempData["alertMessage"] = "No Existen Productos Agrega uno";
                return View("GetAll", result);
            }
            else
            {
                foreach (ML.Producto producto in result.Objects.ToList())
                {
                    pos++;
                    if (producto.IdProducto == Id)
                    {
                        break;
                    }
                }

                result.Objects.RemoveAt(pos - 1);

                return View("GetAll", result);
            }

        }

        public ActionResult IncrementaProduct(int Id)
        {
            ML.Result result = new ML.Result();
            result.Objects = new List<Object>();
            result.Objects = (List<Object>)Session["Carrito"];
           

           foreach (ML.Producto producto in result.Objects)
            {
                
               
                if (producto.IdProducto == Id)
                {
                    
                    producto.Cantidad++;
                    producto.VentaProducto.Venta.Total = producto.VentaProducto.Cantidad * producto.PrecioUnitario;
                    
                    break;
                }
            }

            return View("GetAll", result);

        }

        public ActionResult DecrementaProduct(int id)
        {
            ML.Result result = new ML.Result();
            result.Objects = new List<Object>();
            result.Objects = (List<Object>)Session["Carrito"];

            int pos = 0;
            bool comprobar = false;
            foreach (ML.Producto producto in result.Objects)
            {
                pos++;
                if (producto.IdProducto == id)
                {
                    producto.Cantidad--;
                    producto.VentaProducto.Venta.Total = producto.Cantidad * producto.PrecioUnitario;
                    comprobar = false;
                    if (producto.Cantidad <= 0)
                    {
                        comprobar = true;
                    }
                    break;
                }

            }

            if (comprobar == true)
            {
                result.Objects.RemoveAt(pos - 1);
            }

            return View("GetAll", result);

        }
   
        /*     public ActionResult ListProduct(List<ML.Producto> producto)
        {
            ML.Producto productos = new ML.Producto();
 
 
            if (Session["Carrito"] == null)
            {
                var result = new ML.Result();
                result.Objects = new List<Object>();
                //Existe
                foreach (ML.Producto productoItem in producto)
                {
 
                    if (productoItem.Selected == true)
                    {
                        productos.IdProducto = productoItem.IdProducto;
                        var consult = BL.Producto.GetByIdEF(productos.IdProducto);
 
 
                        result.Objects.Add(consult.Object);
                    }
                    else
                    {
                        //No esta Seleccionado
                    }
 
                }
 
                Session["Carrito"] = result.Objects;
                return View("GetAll", result);
            }
 
            else
            {
                var result = new ML.Result();
                result.Objects = new List<Object>();
                result.Objects = (List<Object>)Session["Carrito"];
                int pos = 0;
 
 
                foreach (ML.Producto productoItem in producto.ToList())
                {
 
                    if (productoItem.Selected == true)
                    {
 
                        if (productoItem.IdProducto == producto[pos].IdProducto)
                        {
                            producto[pos].VentaProducto = new ML.VentaProducto();
                            producto[pos].VentaProducto.Cantidad++;
                             producto[pos].VentaProducto.Venta = new ML.Venta();
                            producto[pos].DetallePedido.Total = producto[pos].DetallePedido.Cantidad * producto[pos].Precio;
                        }
                        else
                        {
                            productos.IdProducto = productoItem.IdProducto;
                            var consult = BL.Producto.ProductoGetById(productos);
                            result.Objects.Add(consult.Object);
                            Session["Carrito"] = result.Objects;
                        }
 
 
                    }
                    else
                    {
                        //No esta Seleccionado
                    }
                    pos++;
                }
                return View("GetAll", result);
 
            }
        }
           * */

        public ActionResult ProcesarCompra()
        {
            ML.Venta venta = new ML.Venta ();
            venta.Cliente = new ML.Cliente();
            venta.Cliente.IdCliente = 1;
            venta.MetodoPago = new ML.MetodoPago();
            venta.MetodoPago.IdMetodoPago = 1;
            

            ML.Result result = new ML.Result();
            result.Objects = new List<object>();
            result.Objects = (List<Object>)Session["Carrito"];

            decimal total = 0;

            foreach (ML.Producto producto in result.Objects.ToList())
            {

Solution1/MVC/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class VentaController : Controller
    {
        // GET: Venta
        [HttpGet]
        public ActionResult ProductoGetAll()
        {
            ML.Result result = BL.Producto.GetAllEF();

            ML.Producto producto = new ML.Producto();
            producto.Productos = result.Objects;

            return View(producto);

        }

        public ActionResult GetAll()
        {
            var result = BL.Producto.GetAllEF();
            List<ML.Producto>ProductoList=new List <ML.Producto>();

            foreach(var productoItem in result.Objects)
            {
                ML.Producto producto = new ML.Producto();
                producto.IdProducto = ((ML.Producto)productoItem).IdProducto;
                producto.Nombre = ((ML.Producto)productoItem).Nombre;
                producto.PrecioUnitario = ((ML.Producto)productoItem).PrecioUnitario;
                producto.Stock = ((ML.Producto)productoItem).Stock;
                producto.Descripcion = ((ML.Producto)productoItem).Descripcion;       
                producto.Imagen = ((ML.Producto)productoItem).Imagen;
                producto.Proveedor = new ML.Proveedor();
                producto.Proveedor.IdProveedor = ((ML.Producto)productoItem).Proveedor.IdProveedor;
                producto.Departamento = new ML.Departamento();
                producto.Departamento.IdDepartamento = ((ML.Producto)productoItem).Departamento.IdDepartamento;

                ProductoList.Add(producto);
            }
            return View(ProductoList);
        }
	}
}

Solution1/MVC/Views/Carrito/GetAll.cshtml
@model ML.Result
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Carrito</h2>

@if (Model.Objects == null)
{
    <div class="">
        <div class="d-flex flex-row-reverse">
            <div class="col-md-12 col-md-offset-10">
                <a href="@Url.Action("GetAll", "Venta")" class="btn btn-success">
                    <i class="fas fa-plus-circle"></i>
                    Añadir Productos
                </a>
            </div>
        </div>

        <br>
    </div>
}
else
{
    <div class="col-md-12">
        <div class="d-flex flex-row-reverse">
            <div class="col-md-offset-10">
                <a href="@Url.Action("GetAll","Venta")" class="btn btn-success">
                    <i class="fas fa-plus-circle"></i>
                    Añadir Mas Productos
                </a>
            </div>
        </div>
        <br>

        <table class="table">

            <thead class="thead-dark">
                <tr>
                    <th scope="col">Imagen</th>
                    <th scope="col">Nombre Producto</th>
                    <th scope="col">Precio</th>
                    <th scope="col"><center>Cantidad</center></th>
                    <th scope="col">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Producto producto in Model.Objects.ToList())
                {
                    <tr>
                        <td style="height:15px; width:15px;">
                            @if (@producto.Imagen == null)
                            {
                                <img style="height: 100%; width:100%;" src="~/DEFAULT.jpg" class="img-responsive">
                            }
                            else
                            {
                                <label> <img style="height: 100%; width:100%;" src="data:image/jpeg;base64,@Convert.ToBase64String(@producto.Imagen)" class="img-responsive" />
                                </label>
                            }
                        </td>
                        <td>
                            <label>@producto.Nombre</label>
                        </td>
                        <td>
                            <label>@producto.PrecioUnitario </label>
                        </td>
                        <td>
                            <a href="@Url.Action("DecrementaProduct", "Carrito", new { id = producto.IdProducto})" class="btn btn-success"> - </a>  
                                     @Html.TextBoxFor(model => producto.Cantidad, new  { Class = "center", disabled = "disabled" })
                            <a href="@Url.Action("IncrementaProduct", "Carrito", new { id = producto.IdProducto })" class="btn btn-success"> + </a>
                        </td>
                        <td>
                            <a id="myBtn" type="button" name="myBtn" class="btn btn-danger" href="@Url.Action("DeleteProduct","Carrito", new {id=producto.IdProducto})"><i class="fas fa-trash"></i>Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="d-flex flex-row-reverse">
            <div class="col-md-offset-10">
                @{
                decimal total = 0;
                foreach (ML.Producto producto in Model.Objects.ToList())
                {
                    producto.VentaProducto = new ML.VentaProducto();
                    producto.VentaProducto.Venta = new ML.Venta();
                   
                    total = total + producto.VentaProducto.Venta.Total;
                }
                <label>Total de la Compra: @total </label>
                }
            </div>
        </div>

        <div class="d-flex flex-row-reverse">
            <div class="col-md-offset-10">
                    <i class="fas fa-money-bill-alt"></i>
                    <a href="@Url.Action("ProcesarCompra", "Carrito")" class="btn btn-success"> <img src="@Url.Content("~/finCompra.jpg")"  />  </a>  

                
            </div>
        </div>

    </div>
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<div class="container">
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Confirmacion</h4>
                </div>
                <div class="modal-body">
                    <center>
                        <p>Seguro que Terminaste de Comprar</p>
                    </center>
                </div>
                <div class="modal-footer">
                    <a href="@Url.Action("GetAll", "DetallePedido")" class="btn btn-success"><i class="fas fa-cash-register"></i>Terminar Compra</a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    function openModal() {
        $("#myModal").modal("show");
    }
</script>